### ISSUE TITLE
Compute Date is not defined

### ISSUE THREAD

**Issue by yooperdude** [OrbitalEnterprises/eve-market-strategies#3]
I'm running the scrap_single_day.py without any modifications to the basic script. An awesome book to dig into some Python. Thank you!

It is returning the following error : 

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\Casey\scrap_single_day.py", line 339, in execution_chunk
    order_book = OrderBook.get_data_frame(dates=[compute_date], types=book_batch, regions=[region_id],
NameError: name 'compute_date' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scrap_single_day.py", line 371, in <module>
    opps_arrays = pool.map(execution_chunk, chunks)
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
NameError: name 'compute_date' is not defined

(base) C:\Users\Casey>


```

**Comment by deadlybulb** [comment]
I'll have to test it tomorrow but it looks like it might be a simple typo.  If you want to try a quick fix, change "dates=[compute_date]" to "dates=[dt]" on line 338 of the script.  I'll do some proper debugging tomorrow.

**Comment by yooperdude** [comment]
That took care of it. Thanks! You put together a really great tutorial/book, very helpful.

**Comment by deadlybulb** [comment]
Reproduced on my end and confirmed fix.  Thanks for reporting.  Enjoy!
